(define (color wavelength)
	(cond ((> wavelength 7000) (display "Infrared"))
		((> wavelength 6470) (display "Red"))
		((> wavelength 5850) (display "Orange"))
		((> wavelength 5750) (display "Yellow"))
		((> wavelength 4912) (display "Green"))
		((> wavelength 4240) (display "Blue"))
		((> wavelength 4000) (display "Violet"))
		(else (display "Ultraviolet"))))
